### ISSUE TITLE
Installation ends with an error

### ISSUE THREAD

**Issue by darktown** [agence-adeliom/easy-seo-bundle#1]
When I run your script it runs through to the point where cache:clear is executed. The following error appears here.

`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In ArrayNode.php line 226:
!!  
!!    The child config "media_entity" under "easy_media" must be configured.  
!!  
!!
!!
Script @auto-scripts was called via post-update-cmd`

From this point on, I can no longer run cache:clear. here the same error occurs again and again.
php version: 8.1.1
Symphony: 5.4
EasyAdmin: 4

**Comment by arnaud-ritti** [comment]
Hi, this issue is related to [agence-adeliom/easy-media-bundle ](https://github.com/agence-adeliom/easy-media-bundle).
You must add the recipes to configure the media bundle. You can copy the following to your project [files](https://github.com/agence-adeliom/symfony-recipes/tree/main/agence-adeliom/easy-media-bundle/2.0) to your project or use our recipes endpoint.

```
{
  "extra": {
    "symfony": {
      "endpoint": [
        "https://api.github.com/repos/agence-adeliom/symfony-recipes/contents/index.json?ref=flex/main",
        ...
        "flex://defaults"
      ],
      "allow-contrib": true
    }
  }
}
```
